[project]
name = "pass-to-txt"
description = "Exports you pass tree to a text file"
requires-python = ">=3.10"
dependencies = []
version = "1.0"
readme = "README.md"

[tool.black]
line-length = 100
target-version = ['py38']

[tool.pyright]
