---
name: CI

on:  # yamllint disable-line rule:truthy
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  push:
    branches: main  # Comment this line to trigger the CI before opening a PR
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        timeout-minutes: 5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            dev-requirements.txt
            pip-requirements.txt
      - name: Install dependencies
        run: |
          # Install pinned pip first, for reproducibility
          pip install -r ${{ github.workspace }}/pip-requirements.txt
          pip install -r ${{ github.workspace }}/dev-requirements.txt

      - name: Formatting
        run: |
          black $(git ls-files "*.py")

      - name: Linting
        run: |
          flake8 $(git ls-files "*.py")

      - name: Linting yaml
        run: |
          yamllint $(git ls-files "*.yaml" "*.yml")

      - name: Typechecking
        run: |
          pyright $(git ls-files "*.py")
